#index:
#    path: /
#    controller: App\Controller\DefaultController::index

libraries:
    path: /library
    controller: App\Controller\LibraryController::getCollection

library:
    path: /library/{id}
    controller: App\Controller\LibraryController::getItem
